### ISSUE TITLE
Playing SE, this does not work from Navigation Satellite mode

### ISSUE THREAD

**Issue by hahn-kev** [Daeruun/LogisticRequestManager#10]
I'm playing space exploration and I'd love to set the requests for a spidertron when using the Navigation Satellite mode, but when I open the gui for this mod or the spidertron the gui does not show it as active so I can't set the requests.

**Comment by Daeruun** [comment]
Sorry for my late response.
This should be fixed with Version 1.1.24 that I uploaded to the mod portal yesterday.
