### ISSUE TITLE
On research finished crashes when some entities are open

### ISSUE THREAD

**Issue by SkyeOfBreeze** [Daeruun/LogisticRequestManager#11]
The LRM mod crashes when the UI for the SE Satellite Receiver, LTN Combinator, Crafting Combinator, or any other entities are open when the research finishes that do not have a logistic point.

**Comment by SkyeOfBreeze** [comment]
I have a potential fix for this that I am currently going to test a little bit first but I will create a PR for what I currently have

**Comment by Daeruun** [comment]
I implemented  the same logic in some more places after your hint - should work fine now.

Thanks again!
