### ISSUE TITLE
Mod crashes when loading preset to chest where an item has maximum set to 0

### ISSUE THREAD

**Issue by jurgyy** [Daeruun/LogisticRequestManager#15]
The game crashes when I try to copy any preset to a requester chest where one of the requested items has a max item count/limit is set to 0, i.e. autotrash.

  The mod Logistic Request Manager (continued) (1.1.28) caused a non-recoverable error.  
  
  Error while running event LogisticRequestManager::on_gui_click (ID 1) count must be positive)  
  stack traceback:  
  [C]: In function 'set_slot'  
  __LogisticRequestManager__/scripts/request-manager.lua:382: in function 'push_request_to_requester'  
  __LogisticRequestManager__/scripts/request-namager.lua:281: in function 'apply_preset'  
  __LogisticRequestManager__/scripts/request-manager.lua:604: in function 'load_preset'  
  __LogisticRequestManager__/control.lua:118 in function <__LogisticRequestManager__/control.lua:48>

Repro:

1. Create a request preset with one or more items requested where at least one of them has a limit set to 0.  
2. Open a requester chest  
3. Open Logistic Request Manager menu and navigate to the preset as defined in step 1.  
4. Click on the "Load preset" button

Screenshot:
![image](https://github.com/Daeruun/LogisticRequestManager/assets/22032197/8d31e6d2-c156-4719-a092-665f737cb2d6)

**Comment by Daeruun** [comment]
Thanks for the report.
I'll fix this asap, but it may take a few days.
