### ISSUE TITLE
LRM does not seem to be multiplayer safe

### ISSUE THREAD

**Issue by Diablo-D3** [Daeruun/LogisticRequestManager#17]
![image](https://github.com/Daeruun/LogisticRequestManager/assets/448731/d9697c82-fb43-4f7a-b627-9858dd6d2ab0)

I can't connect until this mod is removed.

**Comment by Daeruun** [comment]
Hi Diablo-D3,
I can reproduce it. FIxing it may take a few days, as I don't have too much time.
Version 1.27 should work for the time beeing. It has some known bugs, though.

**Comment by Daeruun** [comment]
Thanks for the report!
Interesting thing here. With my mod alone I cannot reproduce this.
Can you give me more information? a complete modlist? Gameversion? mod version? How did you get that error? I have never seen that...

**Comment by Daeruun** [comment]
Could be fixed,...
or could not be. as I cannot reproduce the exact issue and don't have a log to verify i can only guess...

**Comment by Diablo-D3** [comment]
Unfortunately, local log nor server log mentioned anything other than the same error.

It was otherwise a totally normal BobAngel game with nothing weird.

My gaming group is now doing a Py game (wish us luck), and we wont be getting to logistics for another 4 years.
