### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by ntwest** [Daeruun/LogisticRequestManager#6]
This mod offers import/export via strings:
https://mods.factorio.com/mod/PersonalLogisticsImportExport/discussion/5fd0ddafe9d499e685a0ffcb

Could this be merged into this? Or is this functionality already available?

**Comment by Daeruun** [comment]
I'll look into it.

**Comment by Daeruun** [comment]
what exactly would you suggest to add to LRM?
exporting of existing presets
and importing strings into new presets?

please try to give a slightly more detailed usecase (best with desired workflow) ;-)

**Comment by Daeruun** [comment]
Hi, if you are still interessted in this, take a look at the branch [export-import-presets](https://github.com/Daeruun/LogisticRequestManager/tree/export-import-presets) and please give me some feedback here.

**Comment by ntwest** [comment]
Thanks! I'll try a build and will take a look in a few days

**Comment by Daeruun** [comment]
No need to build anything.
Just clone it or until the downloaded branch into a folder named 'LogisticRequestManager' in the 'mods' folder and your ready to test it.
Btw export and import should be compatible to the mod you mentioned.

**Comment by Daeruun** [comment]
I just pushed some changes to the branch to fix a bug that would cause a crash and another that would prevent the gui from opening.

**Comment by Daeruun** [comment]
@ntwest : any thoughts on the layout or the handling of exports/imports?

**Comment by cdcrothers** [comment]
would be particularly nice if the export/import strings were json, so users could leverage their editors of choice to mass update certain types of requests etc (like setting them all to zero or even parsing/modifying the json via their own script in their language of choice.

**Comment by Daeruun** [comment]
sorry, @connorcrothers, I don't think that will happen.
the export string will be - or better already is - a blueprint-string or at least something similar.
Blueprint-json-format is described in the [factorio wiki](https://wiki.factorio.com/Blueprint_string_format#Json_representation_of_a_blueprint.2Fblueprint_book)
there are scripts out there to unpack that.
In that way the string is compatible with other mods and by using the builtin encoding/decoding a lot of parsing is done by the game that I don't want to do myself. 

My table is easier: 
Each table-entry holds a table containing {name, min and max} of one request-slot.
Empty slots are represented by an empty string.
a last table is added at the end, containing an element with the name of the preset - thats it.

An example (the icons may change):

![image](https://user-images.githubusercontent.com/18032264/108434669-5a1d1800-7248-11eb-92c3-46d67cac846f.png)
The preset 'test' containing a request for 50 to unlimited wodden chests in the first slot will be exported as 
> "eNqLrlbKS8xNVbJSKs/PT0nN003OSC0uUdJRys3MU7IyNQAyEiuUrEyMLE0szcyNLE1rdZSUBgBVK/kE+cYXFKUWp5bEQ11cAnJpbSwAY7Yp0w=="

therein is the following json table:
`[{"name":"wooden-chest","min":50,"max":4294967295},"","","","",
"","","","","",
"","","","","",
"","","","","",
"","","","","",
"","","","","",
"","","","","",
"","","","","",
{"LRM_preset_name":"test"}]`

**Comment by Daeruun** [comment]
updated version should be available in the game for 0.18.x/1.0.0 as well as 1.1.x
