### ISSUE TITLE
Request: BP Import should also request items

### ISSUE THREAD

**Issue by SpikesDivZero** [Daeruun/LogisticRequestManager#9]
Given a blueprint ghost with an item request in it (modules, fuel, etc.), importing a BP should also import the item requests for that entity.

Three test cases that come to mind:
* Locomotive with an initial fuel supply (e.g., 10 Rocket Fuel and 5 Coal -- silly example, but highlights edge case)
* Assembler 3 machine with a mix of modules
* Beacon with a mix of modules

It looks like this data is available in [BlueprintEntity.items](https://lua-api.factorio.com/latest/Concepts.html#BlueprintEntity).

```
game.player.print(serpent.dump(
  game.player.get_blueprint_entities()[1].items
))
```

Thanks for the work you've put into this mod. It's been super helpful!

**Comment by Daeruun** [comment]
Sorry I did not respond earlier.
I missed the mail and did not check github manually.

Thanks for using the mod!

Blueprints are actually handled this way. To be sure, I checked all 3 cases and the same with blueprints in a blueprint book.
Locomotion and 3 different fuels work just as fine as the other cases you suggested.

If it does not work for you, please attach a savegame with instructions how to reproduce the issue!

Best regards
Daeruun
